export const imagesAndIcons = {
    arrwLeft : require('../assets/icons/arrwLeft.png'),
    earPods : require('../assets/icons/earPods.png'),
    headPhone: require('../assets/icons/headPhone.png'),
    liked: require('../assets/icons/liked.png'),
    homeIcon: require('../assets/icons/homeIcon.png'),
    ProfileIcon: require('../assets/icons/ProfileIcon.png'),
    notifYellow: require('../assets/icons/notifYellow.png'),
    homeFrame: require('../assets/icons/homeFrame.png'),
    applePay: require('../assets/icons/applePay.png'),
    gPay: require('../assets/icons/gPay.png'),
    paypal : require('../assets/icons/paypal.png'),
    visaIcon: require('../assets/icons/visaIcon.png'),
    good: require('../assets/icons/good.png'),
    favourites: require('../assets/icons/favourites.png'),
    cartIcon : require('../assets/icons/cartIcon.png'),
    searchIcon: require('../assets/icons/searchIcon.png'),
    notificationIcon: require('../assets/icons/notificationIcon.png'),
    starRating: require('../assets/icons/starRating.png'),
    uploadIcon: require('../assets/icons/uploadIcon.png'),
    headSetFront: require('../assets/images/headSetFront.png'),
    headSetBack: require('../assets/images/headSetPack.png'),
    headSetSide: require('../assets/images/headSetSide.png'),
    homePageCardImage: require('../assets/images/homepageCardImage.png'),
    lightening: require('../assets/images/lightening.png'),
    loginPageImage: require('../assets/images/loginPageImage.png'),
    mac : require('../assets/images/mac.png'),
    speaker: require('../assets/images/speaker.png'),
    backgroundLogin: require('../assets/images/backgroundLogin.png')
}